from .InstructorOllama import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .models import *
WEB_DIRECTORY = "./web"
__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']
